# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-XML2JSON
version:      0.02
version_from: lib/XML/XML2JSON.pm
installdirs:  site
requires:
    XML::LibXML:                   1.59

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
